# I need refere nodejs tasks in common folder 
#catalogue is one role 
#common is a another role
#I need import nodejs.yaml in catalogue 

- name: Install NodeJs
  ansible.builtin.import_role:
    name: nodejs
    tasks_from: common
